doctrine:
    dbal:
        driver: pdo_mysql
        charset: UTF8
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Customer:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infra/Repository/Mappers'
                prefix: 'App\Infra\Repository\Mappers'
                alias: Customer
            Transaction:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infra/Repository/Mappers'
                prefix: 'App\Infra\Repository\Mappers'
                alias: Transaction
            Wallet:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infra/Repository/Mappers'
                prefix: 'App\Infra\Repository\Mappers'
                alias: Wallet
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
