doctrine:
    dbal:
        driver: pdo_sqlite
        path: '%kernel.project_dir%/var/data.db3'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infra/Repository/Doctrine'
                prefix: 'App\Infra\Repository\Doctrine'
                alias: User
            Transaction:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infra/Repository/Doctrine'
                prefix: 'App\Infra\Repository\Doctrine'
                alias: Transaction
#    orm:
#        mappings:
#            App:
#                is_bundle: false
#                type: yaml
#                dir: '%kernel.project_dir%/config/doctrine'
#                prefix: 'App\Domain\Entity'
#                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
