#index:
#    path: /
#    controller: App\Controller\DefaultController::index

healthy:
  path: '/api/healthy'
  controller: 'App\Application\Controller\HealthyController::healthy'
  methods: ['GET']

customer:
  path: '/api/customer'
  controller: 'App\Application\Controller\CustomerController::createCustomer'
  methods: ['POST']

Transaction:
  path: '/api/transaction'
  controller: 'App\Application\Controller\TransactionController::createTransaction'
  methods: ['POST']

Deposit:
  path: '/api/wallet/deposit'
  controller: 'App\Application\Controller\WalletController::deposit'
  methods: [ 'POST' ]

Balance:
  path: '/api/wallet/balance/{customerId}'
  controller: 'App\Application\Controller\WalletController::getBalanceByCustomer'
  methods: [ 'GET' ]
  requirements:
    customerId: '\d+'


Extract:
  path: '/api/transaction/extract/{customerId}'
  controller: 'App\Application\Controller\TransactionController::getExtractByCustomer'
  methods: [ 'GET' ]
  requirements:
    customerId: '\d+'

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
