#index:
#    path: /
#    controller: App\Controller\DefaultController::index

healthy:
  path: '/api/healthy'
  controller: 'App\Application\Controller\HealthyController::healthy'
  methods: ['GET']

customer:
  path: '/api/customer'
  controller: 'App\Application\Controller\CustomerController::createCustomer'
  methods: ['POST']

Transaction:
  path: '/api/transaction'
  controller: 'App\Application\Controller\TransactionController::createTransaction'
  methods: ['POST']

Wallet:
  path: '/api/wallet/deposit'
  controller: 'App\Application\Controller\WalletController::deposit'
  methods: [ 'POST' ]

api_platform:
  resource: .
  type: api_platform
  prefix: /api