services:
    App\Application\UseCases\CreateUser:
        arguments:
            $userRepository: '@App\Infrastructure\Doctrine\UserRepository'

#    doctrine.default_metadata_driver:
#        class: Doctrine\ORM\Mapping\Driver\YamlDriver
#        factory: ['Doctrine\ORM\Mapping\Driver\YamlDriver', 'create']
#        arguments:
#            - '%kernel.project_dir%/config/doctrine'