parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    App\Application\Controller\:
        resource: '../src/Application/Controller/'
        tags: ['controller.service_arguments']

    App\Seeds\:
        resource: '../src/Seeds/'
        tags: ['console.command']
