App\Domain\Entity\Transaction:
  type: entity
  table: transactions
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    amount:
      type: float
    operationType:
      type: string
      length: 255
    createdAt:
      type: datetime
  manyToOne:
    payee:
      targetEntity: App\Domain\Entity\User
      joinColumn:
        name: payee_id
        referencedColumnName: id
    payeer:
      targetEntity: App\Domain\Entity\User
      joinColumn:
        name: payeer_id
        referencedColumnName: id