App\Domain\Entity\User:
  type: entity
  repositoryClass: App\Repository\UserRepository
  table: users
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 150
    ssn:
      type: string
      length: 150
      unique: true
    email:
      type: string
      length: 150
      unique: true
    password:
      type: string
      length: 150
    role:
      type: string
      length: 150
    createdAt:
      type: datetime
    updatedAt:
      type: datetime
  lifecycleCallbacks:
    prePersist: [setCreatedAt, setUpdatedAt]
    preUpdate: [setUpdatedAt]
