App\Domain\Entity\Wallet:
  type: entity
  repositoryClass: App\Repository\WalletRepository
  table: wallets
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    accountBalance:
      type: float
    createdAt:
      type: datetime
    updatedAt:
      type: datetime
  oneToOne:
    user:
      targetEntity: App\Domain\Entity\UserEntity
      inversedBy: wallet
      joinColumn:
        name: user_id
        referencedColumnName: id
